### ISSUE TITLE
Implement Debian support

### ISSUE THREAD

**Issue by stdevel** [adfinis/ansible-role-icinga2_web#22]
##### ISSUE TYPE
 - Feature Idea

##### EXPECTED RESULTS
Installing icinga2-web is also possible on Debian-based systems.

##### ACTUAL RESULTS
The role is only supported on Enterprise Linux 7.

**Comment by jon4hz** [comment]
Hey :wave: 
This role now has support for debian 12 and support for EL was dropped.
